/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as RecenziiRouteImport } from './routes/recenzii'
import { Route as PreturiRouteImport } from './routes/preturi'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const RecenziiRoute = RecenziiRouteImport.update({
  id: '/recenzii',
  path: '/recenzii',
  getParentRoute: () => rootRouteImport,
} as any)
const PreturiRoute = PreturiRouteImport.update({
  id: '/preturi',
  path: '/preturi',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/preturi': typeof PreturiRoute
  '/recenzii': typeof RecenziiRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/preturi': typeof PreturiRoute
  '/recenzii': typeof RecenziiRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/preturi': typeof PreturiRoute
  '/recenzii': typeof RecenziiRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/despre'
    | '/faq'
    | '/galerie'
    | '/preturi'
    | '/recenzii'
    | '/servicii'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/despre'
    | '/faq'
    | '/galerie'
    | '/preturi'
    | '/recenzii'
    | '/servicii'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/despre'
    | '/faq'
    | '/galerie'
    | '/preturi'
    | '/recenzii'
    | '/servicii'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  PreturiRoute: typeof PreturiRoute
  RecenziiRoute: typeof RecenziiRoute
  ServiciiRoute: typeof ServiciiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recenzii': {
      id: '/recenzii'
      path: '/recenzii'
      fullPath: '/recenzii'
      preLoaderRoute: typeof RecenziiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preturi': {
      id: '/preturi'
      path: '/preturi'
      fullPath: '/preturi'
      preLoaderRoute: typeof PreturiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  PreturiRoute: PreturiRoute,
  RecenziiRoute: RecenziiRoute,
  ServiciiRoute: ServiciiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
